---
- hosts: '{{ hosts }}'
  remote_user: lana
  become: yes
  become_method: sudo
  tasks:
  - name: install common scripts
    copy: src={{ item }} dest=/usr/local/bin/ owner=root mode=755
    with_fileglob:
    - '{{ my_includes }}/bin/*'
