---
- hosts: ubupc1.ggc.local
  remote_user: lana
  tasks:
  - name: test slack
    local_action:
      module: slack
      token: "{{ slack_token }}"
      username: "{{ slack_user }}"
      msg: "Test posting from ansible playbook"
