---
- hosts: yum
  remote_user: lana
  become: yes
  become_method: sudo
  tasks:
  - name: yum upgrade
    include: tasks/upgrade-yum.yml
    when: ansible_pkg_mgr == "yum"

- hosts: apt
  tasks:
  - name: apt upgrade
    include: tasks/upgrade-apt.yml
    when: ansible_pkg_mgr == "apt"

- hosts: dnf
  tasks:
  - name: dnf upgrade
    include: tasks/upgrade-dnf.yml
    when: ansible_pkg_mgr == "dnf"

- hosts: eopkg
  tasks:
  - name: eopkg update-repo 
    include: tasks/upgrade-eopkg.yml
    when: "pkgmgr" == "eopkg"
