---
- hosts: '{{ hosts }}'
  remote_user: lana
  become: yes
  become_method: sudo
  tasks:
  - name: yum upgrade
    include: tasks/upgrade-yum.yml
    when: ansible_pkg_mgr == "yum"

  - name: apt-upgrade
    include: tasks/upgrade-apt.yml
    when: ansible_pkg_mgr == "apt"

  - name: dnf upgrade
    include: tasks/upgrade-dnf.yml
    when: ansible_pkg_mgr == "dnf"

  - name: eopkg upgrade
    include: tasks/upgrade-eopkg.yml   
    when: pkgmgr == "eopkg"

